//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hallo.WSDL.TestService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.w3schools.com/xml/", ConfigurationName="Hallo.WSDL.TestService.TempConvertSoap")]
    public interface TempConvertSoap
    {
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname Fahrenheit aus Namespace https://www.w3schools.com/xml/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="https://www.w3schools.com/xml/FahrenheitToCelsius", ReplyAction="*")]
        Hallo.WSDL.TestService.FahrenheitToCelsiusResponse FahrenheitToCelsius(Hallo.WSDL.TestService.FahrenheitToCelsiusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.w3schools.com/xml/FahrenheitToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<Hallo.WSDL.TestService.FahrenheitToCelsiusResponse> FahrenheitToCelsiusAsync(Hallo.WSDL.TestService.FahrenheitToCelsiusRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname Celsius aus Namespace https://www.w3schools.com/xml/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="https://www.w3schools.com/xml/CelsiusToFahrenheit", ReplyAction="*")]
        Hallo.WSDL.TestService.CelsiusToFahrenheitResponse CelsiusToFahrenheit(Hallo.WSDL.TestService.CelsiusToFahrenheitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.w3schools.com/xml/CelsiusToFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<Hallo.WSDL.TestService.CelsiusToFahrenheitResponse> CelsiusToFahrenheitAsync(Hallo.WSDL.TestService.CelsiusToFahrenheitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FahrenheitToCelsiusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FahrenheitToCelsius", Namespace="https://www.w3schools.com/xml/", Order=0)]
        public Hallo.WSDL.TestService.FahrenheitToCelsiusRequestBody Body;
        
        public FahrenheitToCelsiusRequest()
        {
        }
        
        public FahrenheitToCelsiusRequest(Hallo.WSDL.TestService.FahrenheitToCelsiusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.w3schools.com/xml/")]
    public partial class FahrenheitToCelsiusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Fahrenheit;
        
        public FahrenheitToCelsiusRequestBody()
        {
        }
        
        public FahrenheitToCelsiusRequestBody(string Fahrenheit)
        {
            this.Fahrenheit = Fahrenheit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FahrenheitToCelsiusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FahrenheitToCelsiusResponse", Namespace="https://www.w3schools.com/xml/", Order=0)]
        public Hallo.WSDL.TestService.FahrenheitToCelsiusResponseBody Body;
        
        public FahrenheitToCelsiusResponse()
        {
        }
        
        public FahrenheitToCelsiusResponse(Hallo.WSDL.TestService.FahrenheitToCelsiusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.w3schools.com/xml/")]
    public partial class FahrenheitToCelsiusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FahrenheitToCelsiusResult;
        
        public FahrenheitToCelsiusResponseBody()
        {
        }
        
        public FahrenheitToCelsiusResponseBody(string FahrenheitToCelsiusResult)
        {
            this.FahrenheitToCelsiusResult = FahrenheitToCelsiusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CelsiusToFahrenheitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CelsiusToFahrenheit", Namespace="https://www.w3schools.com/xml/", Order=0)]
        public Hallo.WSDL.TestService.CelsiusToFahrenheitRequestBody Body;
        
        public CelsiusToFahrenheitRequest()
        {
        }
        
        public CelsiusToFahrenheitRequest(Hallo.WSDL.TestService.CelsiusToFahrenheitRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.w3schools.com/xml/")]
    public partial class CelsiusToFahrenheitRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Celsius;
        
        public CelsiusToFahrenheitRequestBody()
        {
        }
        
        public CelsiusToFahrenheitRequestBody(string Celsius)
        {
            this.Celsius = Celsius;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CelsiusToFahrenheitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CelsiusToFahrenheitResponse", Namespace="https://www.w3schools.com/xml/", Order=0)]
        public Hallo.WSDL.TestService.CelsiusToFahrenheitResponseBody Body;
        
        public CelsiusToFahrenheitResponse()
        {
        }
        
        public CelsiusToFahrenheitResponse(Hallo.WSDL.TestService.CelsiusToFahrenheitResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.w3schools.com/xml/")]
    public partial class CelsiusToFahrenheitResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CelsiusToFahrenheitResult;
        
        public CelsiusToFahrenheitResponseBody()
        {
        }
        
        public CelsiusToFahrenheitResponseBody(string CelsiusToFahrenheitResult)
        {
            this.CelsiusToFahrenheitResult = CelsiusToFahrenheitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TempConvertSoapChannel : Hallo.WSDL.TestService.TempConvertSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TempConvertSoapClient : System.ServiceModel.ClientBase<Hallo.WSDL.TestService.TempConvertSoap>, Hallo.WSDL.TestService.TempConvertSoap
    {
        
        public TempConvertSoapClient()
        {
        }
        
        public TempConvertSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TempConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TempConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TempConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hallo.WSDL.TestService.FahrenheitToCelsiusResponse Hallo.WSDL.TestService.TempConvertSoap.FahrenheitToCelsius(Hallo.WSDL.TestService.FahrenheitToCelsiusRequest request)
        {
            return base.Channel.FahrenheitToCelsius(request);
        }
        
        public string FahrenheitToCelsius(string Fahrenheit)
        {
            Hallo.WSDL.TestService.FahrenheitToCelsiusRequest inValue = new Hallo.WSDL.TestService.FahrenheitToCelsiusRequest();
            inValue.Body = new Hallo.WSDL.TestService.FahrenheitToCelsiusRequestBody();
            inValue.Body.Fahrenheit = Fahrenheit;
            Hallo.WSDL.TestService.FahrenheitToCelsiusResponse retVal = ((Hallo.WSDL.TestService.TempConvertSoap)(this)).FahrenheitToCelsius(inValue);
            return retVal.Body.FahrenheitToCelsiusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hallo.WSDL.TestService.FahrenheitToCelsiusResponse> Hallo.WSDL.TestService.TempConvertSoap.FahrenheitToCelsiusAsync(Hallo.WSDL.TestService.FahrenheitToCelsiusRequest request)
        {
            return base.Channel.FahrenheitToCelsiusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hallo.WSDL.TestService.FahrenheitToCelsiusResponse> FahrenheitToCelsiusAsync(string Fahrenheit)
        {
            Hallo.WSDL.TestService.FahrenheitToCelsiusRequest inValue = new Hallo.WSDL.TestService.FahrenheitToCelsiusRequest();
            inValue.Body = new Hallo.WSDL.TestService.FahrenheitToCelsiusRequestBody();
            inValue.Body.Fahrenheit = Fahrenheit;
            return ((Hallo.WSDL.TestService.TempConvertSoap)(this)).FahrenheitToCelsiusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hallo.WSDL.TestService.CelsiusToFahrenheitResponse Hallo.WSDL.TestService.TempConvertSoap.CelsiusToFahrenheit(Hallo.WSDL.TestService.CelsiusToFahrenheitRequest request)
        {
            return base.Channel.CelsiusToFahrenheit(request);
        }
        
        public string CelsiusToFahrenheit(string Celsius)
        {
            Hallo.WSDL.TestService.CelsiusToFahrenheitRequest inValue = new Hallo.WSDL.TestService.CelsiusToFahrenheitRequest();
            inValue.Body = new Hallo.WSDL.TestService.CelsiusToFahrenheitRequestBody();
            inValue.Body.Celsius = Celsius;
            Hallo.WSDL.TestService.CelsiusToFahrenheitResponse retVal = ((Hallo.WSDL.TestService.TempConvertSoap)(this)).CelsiusToFahrenheit(inValue);
            return retVal.Body.CelsiusToFahrenheitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hallo.WSDL.TestService.CelsiusToFahrenheitResponse> Hallo.WSDL.TestService.TempConvertSoap.CelsiusToFahrenheitAsync(Hallo.WSDL.TestService.CelsiusToFahrenheitRequest request)
        {
            return base.Channel.CelsiusToFahrenheitAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hallo.WSDL.TestService.CelsiusToFahrenheitResponse> CelsiusToFahrenheitAsync(string Celsius)
        {
            Hallo.WSDL.TestService.CelsiusToFahrenheitRequest inValue = new Hallo.WSDL.TestService.CelsiusToFahrenheitRequest();
            inValue.Body = new Hallo.WSDL.TestService.CelsiusToFahrenheitRequestBody();
            inValue.Body.Celsius = Celsius;
            return ((Hallo.WSDL.TestService.TempConvertSoap)(this)).CelsiusToFahrenheitAsync(inValue);
        }
    }
}
